# Default configuration for "fdb" (on linux, /etc/foundationdb.cluster)
lionrock:
  foundationdb:
    clusters:
      # Default cluster
      - name: fdb
#     Example for exposing another cluster by cluster file.
#     - name: another-fdb-cluster
#       clusterFile: /etc/foundationdb/another-fdb-cluster.cluster

spring:
  application:
    name: fdb-facade

# Control logging level (DEBUG for development purposes).
logging:
  level:
    root: INFO

# Below are Wavefront reporting specific entries (need API-token and URL to really work).
management:
  metrics:
    export:
      wavefront:
        enabled: false

wavefront:
  application:
    name: lionrock
    service: fdb-facade

grpc:
  server:
    port: 6565
    reflection-service-enabled: true